[package]
name = "list-todos"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }

aws-sdk-dynamodb = { workspace = true }
lambda_http = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
